version: "3.7"

services:
  tensorflow:
    image: rivia/tensorflow-1:21.09
    hostname: tensorflow
    ports:
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:1234:22"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NOTEBOOK_PASS: "123456"
      NOTEBOOK_USER: "aigroup"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: tensorflow

  pytorch:
    image: rivia/pytorch:21.09
    hostname: pytorch
    ports:
      - "0.0.0.0:18888:8888"
      - "0.0.0.0:11234:22"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NOTEBOOK_PASS: "123456"
      NOTEBOOK_USER: "aigroup"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: pytorch

  tensorrt:
    image: rivia/tensorrt:8.0.3
    hostname: tensorrt
    ports:
      - "0.0.0.0:10001:22"
      - "0.0.0.0:10088:8888"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NVIDIA_VISIBLE_DEVICES: "all"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: tensorrt

  triton_server:
    image: rivia/triton:21.09
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: "10gb"
    hostname: triton_server
    ports:
      - "0.0.0.0:10002:22"
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8001:8001"
      - "0.0.0.0:8002:8002"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NVIDIA_VISIBLE_DEVICES: "all"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: triton_server

  tensorboard:
    image: rivia/tensorflow-1:21.09
    hostname: tensorboard
    ports:
      - "0.0.0.0:6006:6006"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NOTEBOOK_PASS: "123456"
      NOTEBOOK_USER: "aigroup"
    restart: always
    tty: true
    command: tensorboard --logdir=/root/aigroup/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: tensorboard