version: "3.7"

services:
  tensorflow:
    image: aigroup:tensorflow-21.09
    hostname: tensorflow
    ports:
      - "8888:8888"
      - "1234:22"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NOTEBOOK_PASS: "123456"
      NOTEBOOK_USER: "aigroup"
    restart: always
    tty: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: tensorflow

  pytorch:
    image: aigroup:pytorch-21.09
    hostname: pytorch
    ports:
      - "18888:8888"
      - "11234:22"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NOTEBOOK_PASS: "123456"
      NOTEBOOK_USER: "aigroup"
    restart: always
    tty: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: pytorch

  tensorrt:
    image: aigroup:tensorrt-8.0.3
    hostname: tensorrt
    ports:
      - "10001:22"
      - "10088:8888"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NVIDIA_VISIBLE_DEVICES: "all"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: tensorrt

  triton_server:
    image: aigroup:triton-21.09
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: "10gb"
    hostname: triton_server
    ports:
      - "10002:22"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NVIDIA_VISIBLE_DEVICES: "all"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: triton_server

  tensorboard:
    image: aigroup:tensorflow-21.09
    hostname: tensorboard
    ports:
      - "6006:6006"
    volumes:
      - "/data/aigroup:/root/aigroup"
      - "/etc/localtime:/etc/localtime"
    environment:
      ROOT_PASS: "123456"
      NOTEBOOK_PASS: "123456"
      NOTEBOOK_USER: "aigroup"
    restart: always
    tty: true
    command: tensorboard --logdir=/root/aigroup/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
    container_name: tensorboard